name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: print env
      run: echo "${{ secrets.OCCUPY_SECRET }}"

    - name: Make application.yml executable
      run: |
        mkdir ./src/main/resources
        cd ./src/main/resources
#        touch ./application.yml
#        touch ./application-dev.yml
#        chmod +x src/main/resources/application.yml
#        chmod +x src/main/resources/application-dev.yml
        
    - name: Copy Secret
      env:
        OCCUPY_SECRETS: ${{ secrets.OCCUPY_SECRET }}
        OCCUPY_DEV_SECRETS: ${{ secrets.OCCUPY_DEV_SECRETS }}
        OCCUPY_SECRET_DIR: src/main/resources
        OCCUPY_SECRET_FILE: application.yml
        OCCUPY_SECRET_DEV_FILE: application-dev.yml
      run: |
        echo $OCCUPY_SECRETS | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_FILE &&
        echo $OCCUPY_DEV_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DEV_FILE
        find src

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        mysql database: 'iroas'
        mysql user: ${{ secrets.MYSQL_USERNAME }}
        mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#      uses: ./gradlew build
      with:
        arguments: build
